FROM voidlinux/voidlinux:latest
RUN xbps-install --yes -Sy ca-certificates && \
    xbps-install --yes -Sy jq git
COPY run-in-container.sh /run.sh
COPY chive /usr/local/bin/chive
RUN chmod +x /run.sh /usr/local/bin/chive
ENTRYPOINT ["/bin/sh","/run.sh","xbps","sudo xbps-install -S jq"]